cmake_minimum_required(VERSION 3.18 FATAL_ERROR)
project(main)
set(LIBTORCH_DIR "/home/nkw/libtorch")
set(CMAKE_PREFIX_PATH "${LIBTORCH_DIR}")
set(CAFFE2_USE_CUDNN ON)
find_package(Torch REQUIRED)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
file(GLOB_RECURSE SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/include/*.cpp")
add_executable(main main.cpp ${SOURCES})
target_include_directories(main PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(main PRIVATE "${TORCH_LIBRARIES}" icuuc icui18n sentencepiece pthread m dl)
set_target_properties(main PROPERTIES BUILD_RPATH "${LIBTORCH_DIR}/lib" INSTALL_RPATH "${LIBTORCH_DIR}/lib")
